# Generated by Django 2.2.10 on 2021-05-02 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Entity created at datetime', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Entity updated at datetime', verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This will be exposed to the outside world.', unique=True, verbose_name='UUID')),
                ('flavour', models.CharField(choices=[('margarita', 'Margarita'), ('marinara', 'Marinara'), ('salami', 'Salami')], help_text='Flavour of the pizza', max_length=20, verbose_name='Flavour')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size of the pizza', max_length=20, verbose_name='Size')),
                ('quantity', models.IntegerField(help_text='Quantity of the order', verbose_name='Quantity')),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='received', help_text='Delivery status of the order', max_length=20, verbose_name='Delivery Status')),
                ('customer', models.ForeignKey(help_text='The customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.Customer', verbose_name='Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Entity created at datetime', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Entity updated at datetime', verbose_name='Updated At')),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='received', help_text='Delivery status of the order', max_length=20, verbose_name='Delivery Status')),
                ('order', models.ForeignKey(help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_statuses', to='orders.Order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
